---
title: "Final Figure"
author: "Tom Brouwers"
date: "2025-12-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(vegan)
library(patchwork)
library(Polychrome)
library(colorspace)
library(RColorBrewer)
library(ape)
library(readxl)
library(betapart)
library(ggrepel)
library(cowplot)
library(ggh4x)
library(shadowtext)
getwd()
setwd("E:/Msc/Thesis/R")

```

```{r, echo = FALSE}
my_theme <- theme(
  plot.title   = element_text(size = 12, hjust = 0.1),
  axis.text.y    = element_blank(),
  axis.text.x  = element_blank(),
  axis.title   = element_blank(),
  strip.text   = element_blank(),
  legend.title = element_blank(),
  legend.text  = element_text(size = 11),
  legend.position = "right",
  legend.direction = "vertical",
  legend.box = "vertical"
)
```



# Plotting

```{r, echo = False}

p_pop <- p_pop + my_theme
p_toc <- p_toc + my_theme +
  theme(
    legend.position = c(0.98, 0.98),   # near top-right
    legend.justification = c("right", "top"),
    legend.background = element_rect(fill = alpha("white", 0.7))
  )
combined <- combined
plot_shannon_final <- plot_shannon_final+ my_theme
p_abs <- p_abs+ my_theme
p_fluv <- p_fluv+ my_theme +
  theme(
    axis.text.x = element_text(size = 12, face = "bold", angle = 45, vjust = 0.05),
    legend.position = "bottom",
    legend.direction = "horizontal"
  )

p_pop
p_toc
combined
plot_shannon_final
p_abs
p_fluv
```

```{r,echo FALSE}
ggsave("E:/Msc/Thesis/Data/Plots/Final figure/pop_dens.jpg", p_pop, width = 30, height = 3, units = "cm", dpi = 300)
ggsave("E:/Msc/Thesis/Data/Plots/Final figure/p_toc_clean.jpg", p_toc, width = 30, height = 5, units = "cm", dpi = 300)
ggsave("E:/Msc/Thesis/Data/Plots/Final figure/agriculture_clean.jpg", combined, width = 30, height = 10, units = "cm", dpi = 300)
ggsave("E:/Msc/Thesis/Data/Plots/Final figure/shannon.jpg", plot_shannon_final, width = 30, height = 5, units = "cm", dpi = 300)
ggsave("E:/Msc/Thesis/Data/Plots/Final figure/open_taxa.jpg", p_abs, width = 30, height = 5, units = "cm", dpi = 300)
ggsave("E:/Msc/Thesis/Data/Plots/Final figure/p_fluv_clean.jpg", p_fluv, width = 30, height = 7, units = "cm", dpi = 300)
```

